# Generated by Django 5.2 on 2025-05-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth_app', '0003_alter_userprofile_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.TextField(blank=True, default='Nicht angegeben'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, default='Nicht angegeben', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tel',
            field=models.CharField(blank=True, default='Nicht angegeben', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='working_hours',
            field=models.CharField(blank=True, default='Nicht angegeben', max_length=50),
        ),
    ]
