# Generated by Django 5.2 on 2025-05-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_orders_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='offer_pictures/'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
