# Generated by Django 5.2 on 2025-05-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_orders_app', '0002_alter_offer_image_alter_offer_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
