# Generated by Django 5.2 on 2025-05-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_orders_app', '0003_alter_offer_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
